version: "3"

volumes:
  components:
  pages:

services:
  front:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - ./components:/usr/src/app/components
      - ./pages:/usr/src/app/pages